// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzUWp7qJdlhFq4khkIQV-DE0iigKnjmE',
    appId: '1:631126025050:web:e5aeed548d3460f7710963',
    messagingSenderId: '631126025050',
    projectId: 'doancdkhdl',
    authDomain: 'doancdkhdl.firebaseapp.com',
    databaseURL: 'https://doancdkhdl-default-rtdb.firebaseio.com',
    storageBucket: 'doancdkhdl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlZ51Nq3EqJNf-zdmmuZknhtSNNV_43g',
    appId: '1:631126025050:android:c4d8571a36b0343a710963',
    messagingSenderId: '631126025050',
    projectId: 'doancdkhdl',
    databaseURL: 'https://doancdkhdl-default-rtdb.firebaseio.com',
    storageBucket: 'doancdkhdl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-oBH7LRwuERJJ3U2m4wDMSCgU71FIhyM',
    appId: '1:631126025050:ios:1c5510cdd1ca4ce1710963',
    messagingSenderId: '631126025050',
    projectId: 'doancdkhdl',
    databaseURL: 'https://doancdkhdl-default-rtdb.firebaseio.com',
    storageBucket: 'doancdkhdl.appspot.com',
    iosClientId: '631126025050-li9kjb7a6biijfhpu82qs4eeii7cmh7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-oBH7LRwuERJJ3U2m4wDMSCgU71FIhyM',
    appId: '1:631126025050:ios:1c5510cdd1ca4ce1710963',
    messagingSenderId: '631126025050',
    projectId: 'doancdkhdl',
    databaseURL: 'https://doancdkhdl-default-rtdb.firebaseio.com',
    storageBucket: 'doancdkhdl.appspot.com',
    iosClientId: '631126025050-li9kjb7a6biijfhpu82qs4eeii7cmh7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatchat',
  );

}
